spring:
  application:
    name: libraryapi
  profiles:
    active: 
  
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: ${DATASOURCE_URL_AWS}
    username: ${DATASOURCE_USERNAME_AWS}
    password: ${DATASOURCE_PASSWORD_AWS}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: app.log
  level: 
    root: info
    org:
      springframework:
        web: debug
        security: trace
    # Configuração específica para minha API.
    libraryapi: trace

# trace - nível mais detalhado de logs
# debug - depuração, informações de debug
# info - informações gerais sobre o funcionamento normal da aplicação
# warn - indica eventos potencialmente problemáticos
# error - quando dá erro, exception.

# ABAIXO, ACESSAR A PORTA DE METRICAS DA APLICAÇÃO - PARA MONITORAR A APLICAÇÃO.
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*' # '*' está incluindo tudo nas informações.

springdoc:
  override-with-generic-response: false
  

# configuração de production só ativa colocando no active linha 5 
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false


# configuraçao homologação só ativa colocando no active linha 5  
---
spring:
  config:
    activate:
      on-profile: homologacao
  jpa:
    show-sql: false
datasource:
  url: jdbc:postgresql://localhost:5432/library

